// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACfMUlgeOhQlr1bDFnDuSUbCy2aGIPrBE',
    appId: '1:807176765096:web:213a314636fb43ef36cc9d',
    messagingSenderId: '807176765096',
    projectId: 'bigdata-8e95f',
    authDomain: 'bigdata-8e95f.firebaseapp.com',
    storageBucket: 'bigdata-8e95f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBC10A-y1Koy3Y0wk4w9vFrztLifzedU',
    appId: '1:807176765096:android:20ef79cc4df7789936cc9d',
    messagingSenderId: '807176765096',
    projectId: 'bigdata-8e95f',
    storageBucket: 'bigdata-8e95f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53LEI-0n4YXWOuX2O58iN9e2585q80GA',
    appId: '1:807176765096:web:0400aad09c12b28236cc9d',
    messagingSenderId: '807176765096',
    projectId: 'bigdata-8e95f',
    authDomain: 'bigdata-8e95f.firebaseapp.com',
    storageBucket: 'bigdata-8e95f.firebasestorage.app',
  );
}
